Repository athena-scheduler/athena, pull requests merged in 2018-03, with the labels that each got.

#22 Include coverage for main athena assembly
  build/util.cake
Labels: area:build, bug

#20 Add support for docker and docker-compose
  .travis.yml
  Dockerfile
  build.cake
  build/travis.sh
  contrib/wait-postgres.sh
  docker-compose.yml
  tools/packages.config
Labels: area:build, feature

#23 Use Minicover instead of OpenCover
  .gitignore
  build.cake
  build/util.cake
  minicover/minicover.csproj
  src/Athena.Core.Validation/Athena.Core.Validation.csproj
  src/Athena.Core/Athena.Core.csproj
  src/Athena.Data/Athena.Data.csproj
  src/Athena/Athena.csproj
  test/Integration/Athena.Data.Tests/Athena.Data.Tests.csproj
Labels: area:build, feature

#24 Api Controller methods and testing implementation
  Athena.sln
  src/Athena.Core/Repositories/IInstitutionRepository.cs
  src/Athena/Athena.csproj
  src/Athena/Controllers/api/CampusController.cs
  src/Athena/Controllers/api/CampusInstitutionController.cs
  src/Athena/Controllers/api/CourseController.cs
  src/Athena/Controllers/api/InstitutionCampusesController.cs
  src/Athena/Controllers/api/InstitutionController.cs
  src/Athena/Controllers/api/InstitutionCoursesController.cs
  src/Athena/Controllers/api/InstitutionProgramController.cs
  src/Athena/Controllers/api/MeetingController.cs
  src/Athena/Controllers/api/OfferingController.cs
  src/Athena/Controllers/api/OfferingCourseController.cs
  src/Athena/Controllers/api/OfferingMeetingController.cs
  src/Athena/Controllers/api/ProgramController.cs
  src/Athena/Controllers/api/RequirementController.cs
  src/Athena/Controllers/api/RequirementCourseController.cs
  src/Athena/Controllers/api/RequirementProgramController.cs
  src/Athena/Controllers/api/StudentController.cs
  src/Athena/Controllers/api/StudentCoursesController.cs
  src/Athena/Controllers/api/StudentInstitutionController.cs
  src/Athena/Controllers/api/StudentProgramController.cs
  src/Athena/Exceptions/ApiException.cs
  src/Athena/Extensions/RepositoryExtensions.cs
  src/Athena/Setup/Program.cs
  test/Unit/Athena.Tests/Athena.Tests.csproj
  test/Unit/Athena.Tests/ControllerTest.cs
  test/Unit/Athena.Tests/Controllers/Api/CampusControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/CampusInstitutionControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/CourseControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/InstitutionControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/InstitutionCoursesControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/InstitutionProgramControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/InstitutionsCampusesControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/MeetingControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/OfferingControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/OfferingCourseControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/OfferingMeetingControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/ProgramControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/RequirementCourseControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/RequirementProgramControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/RequirementsControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentCoursesControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentInstitutionControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentProgramControllerTests.cs
  test/Unit/Athena.Tests/Extensions/MoqExtensions.cs
Labels: area:backend, feature

#26 Feat/api key auth
  src/Athena.Core/Models/Identity/AthenaRole.cs
  src/Athena.Core/Models/Identity/AthenaUser.cs
  src/Athena.Core/Models/Identity/IUserApiKeyStore.cs
  src/Athena.Data/Extensions/ServiceCollectionExtensions.cs
  src/Athena.Data/Migrations/20180215110432_Identity.cs
  src/Athena.Data/Migrations/20180313154138_ApiKeys.cs
  src/Athena.Data/Migrations/src/20180313154138_ApiKeys.sql
  src/Athena.Data/Repositories/Identity/AthenaUserStore.ApiKeys.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.Email.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.Login.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.Role.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.cs
  src/Athena/Controllers/AccountController.cs
  src/Athena/Controllers/AthenaControllerBase.cs
  src/Athena/Controllers/HomeController.cs
  src/Athena/Controllers/api/AthenaApiController.cs
  src/Athena/Controllers/api/CampusController.cs
  src/Athena/Controllers/api/CampusInstitutionController.cs
  src/Athena/Controllers/api/CourseController.cs
  src/Athena/Controllers/api/InstitutionCampusesController.cs
  src/Athena/Controllers/api/InstitutionController.cs
  src/Athena/Controllers/api/InstitutionCoursesController.cs
  src/Athena/Controllers/api/InstitutionProgramController.cs
  src/Athena/Controllers/api/MeetingController.cs
  src/Athena/Controllers/api/OfferingController.cs
  src/Athena/Controllers/api/OfferingCourseController.cs
  src/Athena/Controllers/api/OfferingMeetingController.cs
  src/Athena/Controllers/api/ProgramController.cs
  src/Athena/Controllers/api/RequirementController.cs
  src/Athena/Controllers/api/RequirementCourseController.cs
  src/Athena/Controllers/api/RequirementProgramController.cs
  src/Athena/Controllers/api/StudentController.cs
  src/Athena/Controllers/api/StudentCoursesController.cs
  src/Athena/Controllers/api/StudentInstitutionController.cs
  src/Athena/Controllers/api/StudentProgramController.cs
  src/Athena/Filters/ApiModelValidationAttribute.cs
  src/Athena/Handlers/ApiKeyHandler.cs
  src/Athena/Middleware/ApiKeyAuthenticationMiddleware.cs
  src/Athena/Middleware/AthenaPrincipalMiddleware.cs
  src/Athena/Middleware/CustomErrorHandlerMiddleware.cs
  src/Athena/Setup/ApplicationBuilderExtensions.cs
  src/Athena/Setup/ServiceCollectionExtensions.cs
  src/Athena/Views/Account/Login.cshtml
  test/Integration/Athena.Data.Tests/Repositories/Identity/AthenaUserStore.Role.cs
  test/Integration/Athena.Data.Tests/Repositories/Identity/AthenaUserStoreTests.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentControllerTests.cs
Labels: area:backend, area:database, feature

#27 Feat/importer
  Athena.sln
  build.cake
  src/Athena.Importer/AbstractImporter.cs
  src/Athena.Importer/Athena.Importer.csproj
  src/Athena.Importer/Dockerfile
  src/Athena.Importer/GenericImporter.cs
  src/Athena.Importer/ObjectMap.cs
  src/Athena.Importer/ObjectMapImporter.cs
  src/Athena.Importer/Program.cs
  src/Athena.Importer/Provider/IDataProvider.cs
  src/Athena.Importer/Provider/IObjectMapProvider.cs
  src/Athena.Importer/Provider/JsonFilesystemDataProvider.cs
  src/Athena.Importer/Provider/JsonFilesystemObjectMapProvider.cs
  src/Athena.Importer/data/campus/lccc-main-campus.json
  src/Athena.Importer/data/campus/toledo-main-campus.json
  src/Athena.Importer/data/campus/uprc.json
  src/Athena.Importer/data/course/eecs3550.json
  src/Athena.Importer/data/course/math2850.json
  src/Athena.Importer/data/course/mthm281.json
  src/Athena.Importer/data/institution/lccc.json
  src/Athena.Importer/data/institution/toledo.json
  src/Athena.Importer/data/meeting/eecs3550-001-s2018-r.json
  src/Athena.Importer/data/meeting/eecs3550-001-s2018-t.json
  src/Athena.Importer/data/meeting/eecs3550-805-s2018-r.json
  src/Athena.Importer/data/meeting/eecs3550-805-s2018-t.json
  src/Athena.Importer/data/meeting/math2850-002-s2018-f.json
  src/Athena.Importer/data/meeting/math2850-002-s2018-m.json
  src/Athena.Importer/data/meeting/math2850-002-s2018-r.json
  src/Athena.Importer/data/meeting/math2850-002-s2018-t.json
  src/Athena.Importer/data/meeting/mthm281-p180-s2018-r.json
  src/Athena.Importer/data/meeting/mthm281-p180-s2018-t.json
  src/Athena.Importer/data/object-map.json
  src/Athena.Importer/data/offering/eecs3550-001-s2018.json
  src/Athena.Importer/data/offering/eecs3550-805-s2018.json
  src/Athena.Importer/data/offering/math2850-002-s2018.json
  src/Athena.Importer/data/offering/mthm281-p180-s2018.json
  src/Athena.Importer/data/program/cse.json
  src/Athena.Importer/data/requirement/multivariable.json
  src/Athena.Importer/data/requirement/software-engineering.json
  src/Athena/Controllers/api/InstitutionCampusesController.cs
  src/Athena/Controllers/api/OfferingCourseController.cs
  src/Athena/Controllers/api/OfferingMeetingController.cs
  src/Athena/Controllers/api/RequirementCourseController.cs
  src/Athena/Controllers/api/RequirementProgramController.cs
  src/Athena/Controllers/api/StudentCoursesController.cs
  src/Athena/Controllers/api/StudentInstitutionController.cs
  src/Athena/Controllers/api/StudentProgramController.cs
  src/Athena/Middleware/CustomErrorHandlerMiddleware.cs
  src/Athena/wwwroot/images/UT-color-vert-trans.gif
  src/Athena/wwwroot/images/owl icon - with label.svg
  src/Athena/wwwroot/images/owl icon.svg
  test/Unit/Athena.Importer.Tests/Athena.Importer.Tests.csproj
  test/Unit/Athena.Importer.Tests/GenericImporterTests.cs
  test/Unit/Athena.Importer.Tests/ObjectMapImporterTests.cs
  test/Unit/Athena.Importer.Tests/ProgramTests.cs
Labels: area:backend, feature

#28 Refactor authentication to allow calling the API from frontend browsers
  src/Athena/Extensions/PrincipalExtensions.cs
  src/Athena/Handlers/ApiKeyHandler.cs
  src/Athena/Middleware/ApiAuthenticationMiddleware.cs
  src/Athena/Middleware/ApiKeyAuthenticationMiddleware.cs
  src/Athena/Middleware/AthenaPrincipalMiddleware.cs
  src/Athena/Setup/ApplicationBuilderExtensions.cs
Labels: area:backend, area:frontend, feature

#29 Feat/miniprofiler
  src/Athena.Core/Models/Identity/AthenaRole.cs
  src/Athena.Data/Athena.Data.csproj
  src/Athena.Data/Extensions/ServiceCollectionExtensions.cs
  src/Athena/Athena.csproj
  src/Athena/Extensions/RequestExtensions.cs
  src/Athena/Middleware/ApiAuthenticationMiddleware.cs
  src/Athena/Middleware/AthenaPrincipalMiddleware.cs
  src/Athena/Setup/ApplicationBuilderExtensions.cs
  src/Athena/Setup/ServiceCollectionExtensions.cs
  src/Athena/Views/Shared/_Layout.cshtml
  src/Athena/Views/_ViewImports.cshtml
Labels: area:backend, feature

#30 Front end mvc
  Athena.sln
  src/Athena/Content/css/site.css
  src/Athena/Views/Home/Add_Classes.cshtml
  src/Athena/Views/Home/Index.cshtml
  src/Athena/Views/Home/Schedule_Page.cshtml
  src/Athena/Views/Home/User_Page.cshtml
  src/Athena/Views/Shared/_Layout.cshtml
  src/Athena/Views/Shared/_Nav.cshtml
Labels: area:frontend, enhancement

#43 fixes for nav-bar chip coloring and addition of button tool-tips
  src/Athena/Content/css/site.css
  src/Athena/Views/Shared/_Nav.cshtml
Labels: area:frontend, enhancement

#45 the home page has had spelling errors fixed and upon logging in shows profile info
  src/Athena/Views/Home/Home.cshtml
  src/Athena/Views/Shared/_CurrentSchedule.cshtml
  src/Athena/Views/Shared/_CurrentScheduleModal.cshtml
  src/Athena/Views/Shared/_StudentDetails.cshtml
Labels: area:frontend, bug, enhancement

#49 New User setup
  src/Athena.Core/Repositories/IInstitutionRepository.cs
  src/Athena.Core/Repositories/IProgramRepository.cs
  src/Athena.Core/Repositories/ISearchableRepository.cs
  src/Athena.Core/Repositories/ProgramSearchOptions.cs
  src/Athena.Data/Repositories/InstitutionRepository.cs
  src/Athena.Data/Repositories/ProgramRepository.cs
  src/Athena/Content/css/site.css
  src/Athena/Content/js/studentSetup.js
  src/Athena/Controllers/AccountController.cs
  src/Athena/Controllers/AthenaControllerBase.cs
  src/Athena/Controllers/HomeController.cs
  src/Athena/Controllers/StudentController.cs
  src/Athena/Controllers/api/InstitutionController.cs
  src/Athena/Controllers/api/ProgramController.cs
  src/Athena/Controllers/api/StudentInstitutionController.cs
  src/Athena/Views/Home/Add_Classes.cshtml
  src/Athena/Views/Home/Schedule_Page.cshtml
  src/Athena/Views/Home/User_Page.cshtml
  src/Athena/Views/Shared/_Layout.cshtml
  src/Athena/Views/Shared/_Nav.cshtml
  src/Athena/Views/Student/Profile.cshtml
  src/Athena/Views/Student/UserSetup.cshtml
  src/Athena/webpack.common.js
  test/Integration/Athena.Data.Tests/DataTest.cs
  test/Integration/Athena.Data.Tests/Repositories/InstitutionRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/ProgramRepositoryTests.cs
  test/Unit/Athena.Tests/Controllers/Api/InstitutionControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/ProgramControllerTests.cs
Labels: area:frontend, feature

#52 fixed the times column loading in incorrectly on the home page
  src/Athena/Views/Home/Home.cshtml
Labels: area:frontend, bug

#50 Do not allow duplicate entries in relationship tables
  src/Athena.Data/Migrations/20180322190011_DropDuplicateLinks.cs
  src/Athena.Data/Migrations/src/20180322190011_DropDuplicateLinks.sql
  src/Athena.Data/Repositories/CampusRepository.cs
  src/Athena.Data/Repositories/CourseRepository.cs
  src/Athena.Data/Repositories/InstitutionRepository.cs
  src/Athena.Data/Repositories/ProgramRepository.cs
  src/Athena.Data/Repositories/StudentRepository.cs
  test/Integration/Athena.Data.Tests/Repositories/CampusRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/CourseRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/InstitutionRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/MeetingRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/OfferingRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/ProgramRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/StudentRepositoryTests.cs
Labels: area:backend, bug

#53 WebHost: Wait for the database to become ready before attempting to run migrations
  src/Athena.Data/EnvironmentVariableConnectionStringProvider.cs
  src/Athena.Data/Extensions/ServiceCollectionExtensions.cs
  src/Athena.Data/IConnectionStringProvider.cs
  src/Athena/Athena.csproj
  src/Athena/Setup/ApplicationBuilderExtensions.cs
  src/Athena/Setup/Program.cs
Labels: area:backend, area:frontend, bug

#55 Add framework for pictures for login providers
  src/Athena/Content/css/site.css
  src/Athena/Content/images/signin_google.png
  src/Athena/Helpers/LoginProviderLogoTagHelper.cs
  src/Athena/Setup/ApplicationBuilderExtensions.cs
  src/Athena/Views/Account/Login.cshtml
  src/Athena/Views/_ViewImports.cshtml
Labels: area:frontend, feature

#56 Feat/gh 54 microsoft auth
  README.md
  src/Athena/Content/css/site.css
  src/Athena/Content/images/signin_google.png
  src/Athena/Content/images/signin_microsoft.png
  src/Athena/Helpers/LoginProviderLogoTagHelper.cs
  src/Athena/Setup/ServiceCollectionExtensions.cs
  src/Athena/Views/Account/Login.cshtml
Labels: area:backend, area:frontend, feature

#57 Refactor Offering and Meeting models in prep for #46
  src/Athena.Core.Validation/Extensions/RuleBuilderExtensions.cs
  src/Athena.Core.Validation/OfferingValidator.cs
  src/Athena.Core/Models/Meeting.cs
  src/Athena.Core/Models/Offering.cs
  src/Athena.Core/Repositories/ICourseRepository.cs
  src/Athena.Core/Repositories/IOfferingReository.cs
  src/Athena.Data/Migrations/20180329115355_RefactorOfferings.cs
  src/Athena.Data/Migrations/20180329131603_InProgressOfferings.cs
  src/Athena.Data/Migrations/20180329144035_FixOfferingMeetingRelationship.cs
  src/Athena.Data/Migrations/src/20180329115355_RefactorOfferings.sql
  src/Athena.Data/Migrations/src/20180329131603_InProgressOfferings.sql
  src/Athena.Data/Migrations/src/20180329144035_FixOfferingMeetingRelationship.sql
  src/Athena.Data/Repositories/CourseRepository.cs
  src/Athena.Data/Repositories/MeetingRepository.cs
  src/Athena.Data/Repositories/OfferingRepository.cs
  src/Athena.Importer/GenericImporter.cs
  src/Athena.Importer/ObjectMap.cs
  src/Athena.Importer/ObjectMapImporter.cs
  src/Athena.Importer/OfferingImporter.cs
  src/Athena.Importer/Program.cs
  src/Athena.Importer/data/meeting/eecs3550-001-s2018-r.json
  src/Athena.Importer/data/meeting/eecs3550-001-s2018-t.json
  src/Athena.Importer/data/meeting/eecs3550-805-s2018-r.json
  src/Athena.Importer/data/meeting/eecs3550-805-s2018-t.json
  src/Athena.Importer/data/meeting/math2850-002-s2018-f.json
  src/Athena.Importer/data/meeting/math2850-002-s2018-m.json
  src/Athena.Importer/data/meeting/math2850-002-s2018-r.json
  src/Athena.Importer/data/meeting/math2850-002-s2018-t.json
  src/Athena.Importer/data/meeting/mthm281-p180-s2018-r.json
  src/Athena.Importer/data/meeting/mthm281-p180-s2018-t.json
  src/Athena.Importer/data/object-map.json
  src/Athena.Importer/data/offering/eecs3550-001-s2018.json
  src/Athena.Importer/data/offering/eecs3550-805-s2018.json
  src/Athena.Importer/data/offering/math2850-002-s2018.json
  src/Athena.Importer/data/offering/mthm281-p180-s2018.json
  src/Athena/Controllers/api/OfferingCourseController.cs
  src/Athena/Controllers/api/OfferingMeetingController.cs
  src/Athena/Controllers/api/StudentCoursesController.cs
  src/Athena/Controllers/api/StudentOfferingsController.cs
  src/Athena/package-lock.json
  test/Integration/Athena.Data.Tests/Repositories/CourseRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/MeetingRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/OfferingRepositoryTests.cs
  test/Unit/Athena.Core.Validation.Tests/OfferingValidatorTests.cs
  test/Unit/Athena.Importer.Tests/ObjectMapImporterTests.cs
  test/Unit/Athena.Importer.Tests/OfferingImporterTests.cs
  test/Unit/Athena.Tests/Controllers/Api/OfferingCourseControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/OfferingMeetingControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentCoursesControllerTests.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentOfferingsControllerTests.cs
Labels: area:backend, area:database, enhancement
