Repository athena-scheduler/athena, pull requests merged in 2018-04, with the labels that each got.

#59 Hotfix: Fix issues from offering refactor
  src/Athena.Data/DbConnectionExtensions.cs
  src/Athena.Data/Extensions/DbConnectionExtensions.cs
  src/Athena.Data/Repositories/MeetingRepository.cs
  src/Athena.Importer/OfferingImporter.cs
  src/Athena.Importer/Program.cs
  test/Integration/Athena.Data.Tests/DataTest.cs
  test/Integration/Athena.Data.Tests/Repositories/MeetingRepositoryTests.cs
  test/Unit/Athena.Importer.Tests/OfferingImporterTests.cs
Labels: area:backend, area:database, bug

#65 Docker: Make a sample db with test data pre-loaded
  build.cake
  src/Athena.Importer/contrib/docker/Dockerfile
  src/Athena.Importer/contrib/docker/import.sh
  src/Athena/Setup/ApplicationBuilderExtensions.cs
Labels: area:backend, area:build, area:database, feature

#68 Mark Courses as Complete or Incomplete from Student Profile
  src/Athena.Core/Repositories/CourseSearchOptions.cs
  src/Athena.Core/Repositories/ICourseRepository.cs
  src/Athena.Data/Repositories/CourseRepository.cs
  src/Athena/Athena.csproj
  src/Athena/Content/css/site.css
  src/Athena/Content/js/ConfigureCompletedCourses.js
  src/Athena/Controllers/StudentController.cs
  src/Athena/Controllers/api/StudentCoursesController.cs
  src/Athena/Views/Student/ConfigureCompletedCourses.cshtml
  src/Athena/Views/Student/Profile.cshtml
  src/Athena/package-lock.json
  src/Athena/webpack.common.js
  test/Integration/Athena.Data.Tests/Repositories/CourseRepositoryTests.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentCoursesControllerTests.cs
Labels: area:backend, area:database, area:frontend, feature

#72 build: Push athenascheduler/db image in push task
  build.cake
Labels: area:build, bug

#70 Issue#31
  src/Athena/Views/Home/Home.cshtml
Labels: area:frontend, enhancement

#73 Fix importer
  src/Athena.Importer/Program.cs
Labels: area:backend, area:build, bug

#78 Combine lecture and lab sections
  src/Athena.Importer/data/offering/eecs1000-001-f2018.json
  src/Athena.Importer/data/offering/eecs1000-002-f2018.json
  src/Athena.Importer/data/offering/eecs1000-805-f2018.json
  src/Athena.Importer/data/offering/eecs1000-806-f2018.json
  src/Athena.Importer/data/offering/eecs1100-001-f2018.json
  src/Athena.Importer/data/offering/eecs1100-002-f2018.json
  src/Athena.Importer/data/offering/eecs1100-805-f2018.json
  src/Athena.Importer/data/offering/eecs1100-806-f2018.json
  src/Athena.Importer/data/offering/eecs3100-001-f2018.json
  src/Athena.Importer/data/offering/eecs3100-002-f2018.json
  src/Athena.Importer/data/offering/eecs3100-805-f2018.json
  src/Athena.Importer/data/offering/eecs3100-806-f2018.json
  src/Athena.Importer/data/offering/eecs3400-001-f2018.json
  src/Athena.Importer/data/offering/eecs3400-002-f2018.json
  src/Athena.Importer/data/offering/eecs3400-805-f2018.json
  src/Athena.Importer/data/offering/eecs3400-806-f2018.json
  src/Athena.Importer/data/offering/phyc251-p111-f2018.json
  src/Athena.Importer/data/offering/phyc251-p611-f2018.json
  src/Athena.Importer/data/offering/phyc252-p181-f2018.json
  src/Athena.Importer/data/offering/phyc252-p611-f2018.json
Labels: area:backend, area:build, bug

#80 these should be all of the requirements and prereqs
  src/Athena.Importer/data/course/mthm181.json
  src/Athena.Importer/data/course/mthm182.json
  src/Athena.Importer/data/object-map.json
  src/Athena.Importer/data/offering/mthm181-p180-f2018.json
  src/Athena.Importer/data/offering/mthm182-p180-f2018.json
  src/Athena.Importer/data/requirement/calc-i.json
Labels: area:backend, area:database, feature

#81 Feat/gh 46 make scheduler writable
  src/Athena.Core/Repositories/CourseSearchOptions.cs
  src/Athena.Data/Repositories/CourseRepository.cs
  src/Athena/Content/css/nav.css
  src/Athena/Content/css/schedule.css
  src/Athena/Content/css/site.css
  src/Athena/Content/js/schedule.js
  src/Athena/Content/js/site.js
  src/Athena/Controllers/api/ScheduleController.cs
  src/Athena/Views/Home/Home.cshtml
  src/Athena/Views/Schedule/ScheduleEditor.cshtml
  src/Athena/Views/Shared/_CurrentSchedule.cshtml
  src/Athena/Views/Shared/_CurrentScheduleModal.cshtml
  src/Athena/package-lock.json
  src/Athena/package.json
  src/Athena/webpack.common.js
  test/Integration/Athena.Data.Tests/Repositories/CourseRepositoryTests.cs
Labels: area:backend, area:database, area:frontend, enhancement

#86 Extend login expiry to 1 hour and make it sliding by default
  src/Athena/Setup/ServiceCollectionExtensions.cs
  test/Unit/Athena.Importer.Tests/OfferingImporterTests.cs
Labels: area:backend, bug

#87 Iss/gh 62 fkey exceptions
  src/Athena.Core/Exceptions/DependentObjectException.cs
  src/Athena.Data/Extensions/DbConnectionExtensions.cs
  src/Athena.Data/Repositories/CampusRepository.cs
  src/Athena.Data/Repositories/CourseRepository.cs
  src/Athena.Data/Repositories/Identity/AthenaRoleStore.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.Login.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.Role.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.cs
  src/Athena.Data/Repositories/InstitutionRepository.cs
  src/Athena.Data/Repositories/MeetingRepository.cs
  src/Athena.Data/Repositories/OfferingRepository.cs
  src/Athena.Data/Repositories/ProgramRepository.cs
  src/Athena.Data/Repositories/RequirementRepository.cs
  src/Athena.Data/Repositories/StudentRepository.cs
  src/Athena/Middleware/CustomErrorHandlerMiddleware.cs
Labels: area:backend, area:database, bug

#91 Colorize offerings
  src/Athena/Content/js/schedule.js
Labels: area:frontend, enhancement

#85 Issue #75
  src/Athena/Content/css/site.css
  src/Athena/Views/Home/Home.cshtml
  src/Athena/Views/Shared/_StudentDetails.cshtml
  src/Athena/package-lock.json
Labels: area:frontend, enhancement

#96 Scheduler: Prevent the student from enrolling in conflicting timeslots
  src/Athena.Core/Models/Meeting.cs
  src/Athena/Content/css/schedule.css
  src/Athena/Content/js/schedule.js
  src/Athena/Controllers/api/StudentOfferingsController.cs
  src/Athena/Exceptions/ApiException.cs
  src/Athena/Middleware/CustomErrorHandlerMiddleware.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentOfferingsControllerTests.cs
Labels: area:backend, area:frontend, enhancement

#98 home schedule x's removed
  src/Athena/Content/js/schedule.js
  src/Athena/Views/Home/Home.cshtml
  src/Athena/package-lock.json
Labels: area:frontend, bug

#100 finish button for add/drop
  src/Athena/Views/Student/ConfigureCompletedCourses.cshtml
Labels: area:frontend, enhancement

#104 Prevent students from enrolling in courses with unmet dependencies
  src/Athena.Core/Repositories/IRequirementRepository.cs
  src/Athena.Data/Repositories/RequirementRepository.cs
  src/Athena/Content/js/schedule.js
  src/Athena/Controllers/api/StudentOfferingsController.cs
  src/Athena/Exceptions/BadModelException.cs
  src/Athena/Exceptions/OfferingConflictException.cs
  src/Athena/Exceptions/UnmetDependencyException.cs
  src/Athena/Extensions/EnumerableExtensions.cs
  src/Athena/Middleware/CustomErrorHandlerMiddleware.cs
  src/Athena/Views/Schedule/ScheduleEditor.cshtml
  src/Athena/Views/Schedule/_UnmetDependencyError.cshtml
  test/Integration/Athena.Data.Tests/Repositories/RequirementRepositoryTests.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentOfferingsControllerTests.cs
Labels: area:backend, area:database, area:frontend, enhancement

#106 Prevent courses registering requirements as both prereqs and concurent prereqs
  src/Athena.Core/Exceptions/IllegalPrerequisiteException.cs
  src/Athena.Data/Migrations/20180412163557_EnsureConcurrentPrereqsAreNotRegularPrereqs.cs
  src/Athena.Data/Migrations/src/20180412163557_EnsureConcurrentPrereqsAreNotRegularPrereqs.sql
  src/Athena.Data/Repositories/CourseRepository.cs
  test/Integration/Athena.Data.Tests/Repositories/CourseRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/MeetingRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/OfferingRepositoryTests.cs
  test/Integration/Athena.Data.Tests/Repositories/RequirementRepositoryTests.cs
Labels: area:backend, area:database, enhancement

#107 Fix duplicate entries in unmet dependency warnings
  src/Athena/Content/js/schedule.js
  src/Athena/Extensions/EnumerableExtensions.cs
  src/Athena/Views/Schedule/_UnmetDependencyError.cshtml
Labels: area:frontend, bug

#109 Identity: track security stamp to fix login timeouts
  src/Athena.Core/Models/Identity/AthenaUser.cs
  src/Athena.Data/Migrations/20180414114233_IdentityTrackSecurityStamps.cs
  src/Athena.Data/Migrations/src/20180414114233_IdentityTrackSecurityStamps.sql
  src/Athena.Data/Repositories/Identity/AthenaUserStore.ApiKeys.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.Email.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.Login.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.Role.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.SecurityStamp.cs
  src/Athena.Data/Repositories/Identity/AthenaUserStore.cs
  test/Integration/Athena.Data.Tests/Repositories/Identity/AthenaUserStore.RoleTests.cs
  test/Integration/Athena.Data.Tests/Repositories/Identity/AthenaUserStore.SecurityStampTests.cs
Labels: area:backend, area:database, bug

#111 Feat/gh 108 focus search bars
  src/Athena/Content/js/ConfigureCompletedCourses.js
  src/Athena/Content/js/schedule.js
  src/Athena/Content/js/studentSetup.js
  src/Athena/Content/js/utils.js
Labels: area:frontend, enhancement

#117 Remove old, unused views
  src/Athena/Controllers/HomeController.cs
  src/Athena/Views/Home/Add_Classes.cshtml
  src/Athena/Views/Home/Schedule_Page.cshtml
Labels: area:frontend, enhancement

#116 Sort meeting dates in scheduler search results
  src/Athena/Content/js/schedule.js
Labels: area:frontend, enhancement

#115 Fix searching for programs
  src/Athena.Core/Repositories/ProgramSearchOptions.cs
  src/Athena.Data/Repositories/ProgramRepository.cs
  src/Athena/Content/js/studentSetup.js
  src/Athena/Controllers/api/ProgramController.cs
  src/Athena/package-lock.json
  test/Integration/Athena.Data.Tests/Repositories/ProgramRepositoryTests.cs
  test/Unit/Athena.Tests/Controllers/Api/ProgramControllerTests.cs
Labels: area:backend, area:frontend, bug

#114 Feat/gh 66 start new schedule
  src/Athena.Core/Repositories/ICourseRepository.cs
  src/Athena.Data/Repositories/CourseRepository.cs
  src/Athena/Content/js/schedule.js
  src/Athena/Controllers/api/ScheduleController.cs
  src/Athena/Views/Shared/_CurrentSchedule.cshtml
  src/Athena/Views/Shared/_CurrentScheduleModal.cshtml
  test/Integration/Athena.Data.Tests/Repositories/CourseRepositoryTests.cs
Labels: area:backend, area:database, area:frontend, enhancement

#119 Fixed test data
  src/Athena.Importer/data/offering/ecnm151-v401-f2018.json
  src/Athena.Importer/data/offering/mthm280-p100-f2018.json
  src/Athena.Importer/data/offering/mthm283-p100-s2018.json
Labels: area:frontend, bug

#120 Update docker-compose example and add documentation for it
  .gitignore
  README.md
  auth-keys.env.sample
  docker-compose.yml
Labels: area:build, enhancement

#125 Minor Style Tweaks
  src/Athena/Content/css/footer.css
  src/Athena/Content/js/studentSetup.js
  src/Athena/Views/Shared/_CurrentSchedule.cshtml
Labels: area:frontend, bug, enhancement

#127 Make the scheduler more readable by tweaking titles and tooltips
  src/Athena/Content/css/site.css
  src/Athena/Content/js/schedule.js
  src/Athena/Models/ScheduleEntry.cs
Labels: area:frontend, bug

#128 Fixing concurrent pre-req dialouge
  src/Athena/Content/js/schedule.js
  src/Athena/Views/Schedule/_UnmetDependencyError.cshtml
Labels: area:frontend, enhancement

#144 Enroll: Exclude offerings with external meetings from conflict checks
  src/Athena/Extensions/EnumerableExtensions.cs
  test/Unit/Athena.Tests/Controllers/Api/StudentOfferingsControllerTests.cs
Labels: area:backend, bug

#143 I beautified the profile page real nice like
  src/Athena/Controllers/AccountController.cs
  src/Athena/Controllers/StudentController.cs
  src/Athena/Views/Student/ConfigureCompletedCourses.cshtml
  src/Athena/Views/Student/Profile.cshtml
  src/Athena/Views/Student/UserSetup.cshtml
  src/Athena/Views/Student/_ConfigureCompletedCourses.cshtml
  src/Athena/Views/Student/_ConfigureInstitutions.cshtml
  src/Athena/Views/Student/_ConfigurePrograms.cshtml
Labels: area:frontend, enhancement

#147 Search Results: group in rows of 3
  src/Athena/Content/js/ConfigureCompletedCourses.js
  src/Athena/Content/js/schedule.js
  src/Athena/Content/js/studentSetup.js
  src/Athena/Content/js/utils.js
Labels: area:frontend, enhancement

#149 Add descriptions for external courses
  src/Athena/Content/js/schedule.js
Labels: area:frontend, enhancement

#150 Remove unused route
  src/Athena/Controllers/StudentController.cs
Labels: area:backend, bug

#151 Minor Style Tweaks
  src/Athena/Content/css/site.css
  src/Athena/Content/js/schedule.js
  src/Athena/Views/Home/Home.cshtml
Labels: area:frontend, bug, enhancement

#152 Remove degree progress bar
  src/Athena/Content/css/site.css
  src/Athena/Views/Home/Home.cshtml
  src/Athena/Views/Shared/_StudentDetails.cshtml
Labels: area:frontend, enhancement

#154 Schedule button to schedule
  src/Athena/Content/js/schedule.js
  src/Athena/Views/Home/Home.cshtml
  src/Athena/Views/Home/_UnmetDependencyError.cshtml
  src/Athena/Views/Schedule/ScheduleEditor.cshtml
  src/Athena/Views/Shared/_CurrentSchedule.cshtml
  src/Athena/Views/Shared/_Nav.cshtml
Labels: area:frontend, enhancement

#159 Fix overlay for unmet dependencies
  src/Athena/Content/js/schedule.js
  src/Athena/Controllers/ScheduleController.cs
Labels: area:frontend, bug

#160 Fix phrasing and scroll issues on profile page
  src/Athena/Content/css/site.css
  src/Athena/Views/Student/Profile.cshtml
  src/Athena/Views/Student/_ConfigureCompletedCourses.cshtml
Labels: area:frontend, bug

#163 Requirement loop fix
  src/Athena.Importer/data/course/eecs3150.json
  src/Athena.Importer/data/object-map.json
Labels: area:backend, area:build, area:database, bug

#166 Fix X-Forwarded-Proto support
  src/Athena/Setup/ApplicationBuilderExtensions.cs
  src/Athena/Setup/ServiceCollectionExtensions.cs
  src/Athena/package-lock.json
Labels: area:backend, bug

#169 Add save button to profile page and focus search inputs when sections expand
  src/Athena/Views/Student/Profile.cshtml
Labels: area:frontend, enhancement, feature

#172 Fix 'agree' button and wording on front page
  src/Athena/Views/Home/Home.cshtml
  src/Athena/Views/Shared/_CurrentScheduleModal.cshtml
Labels: area:frontend, bug, enhancement

#174 Fix dep check order and some issues with the test data
  src/Athena.Importer/data/offering/phyc251-p111-f2018.json
  src/Athena.Importer/data/offering/phyc252-p181-f2018.json
  src/Athena/Controllers/api/StudentOfferingsController.cs
Labels: area:backend, bug

#179 Redirect client side if the user's session expires
  src/Athena/Content/js/ConfigureCompletedCourses.js
  src/Athena/Content/js/schedule.js
  src/Athena/Content/js/studentSetup.js
  src/Athena/Views/Shared/_Layout.cshtml
Labels: area:frontend, bug, enhancement

#180 spelling error inuitive
  src/Athena/Views/Home/Home.cshtml
Labels: area:frontend, bug
